import { TenantPlaceSeed } from '../types';

export const tienThangPlaces: TenantPlaceSeed[] = [
  {
    name: 'Đình Bạch Trữ',
    categoryCode: 'ARCHITECTURE',
    summary: 'Đình Bạch Trữ xây vào cuối thế kỷ 17, thờ phụng Mỵ Nương và Hoàng Cống Sơn.',
    description: 'Đình Bạch Trữ thờ Công chúa Thiên Tiên Mỵ Nương và Hoàng Cống Sơn. Đây là công trình kiến trúc nghệ thuật điêu khắc gỗ tinh xảo thời Lê Trung Hưng còn lưu giữ được nguyên vẹn.',
    latitude: 21.2018,
    longitude: 105.6925,
    bestTime: 'Sáng sớm hoặc dịp lễ hội truyền thống đầu xuân.',
    localTip: 'Hãy chiêm ngưỡng những nét chạm khắc đầu đao gỗ thời Lê cổ kính ẩn sâu dưới mái đình.',
    address: 'Thôn Bạch Trữ, Xã Tiến Thắng, Mê Linh, Hà Nội',
    priceLevel: 'FREE',
    galleryCaptions: [
      'Cổng đình Bạch Trữ cổ kính',
      'Sân đình và mái ngói',
      'Bên trong chính điện thờ tự',
    ],
    published: true,
  },
  {
    name: 'Đình làng Phú Mỹ',
    categoryCode: 'ARCHITECTURE',
    summary: 'Đình Phú Mỹ thờ nhị vị tướng quân của Hai Bà Trưng là Hùng Bảo và Trần Nương.',
    description: 'Đình làng Phú Mỹ là một di tích lịch sử cấp Quốc gia nổi bật, thờ cúng nhị vị tướng quân Hùng Bảo và Trần Nương dưới trướng Hai Bà Trưng.',
    latitude: 21.2085,
    longitude: 105.6525,
    bestTime: 'Sáng sớm hoặc chiều mát các ngày trong tuần.',
    localTip: 'Nên mặc trang phục trang nghiêm và đi nhẹ nói khẽ khi tham quan di tích lịch sử.',
    address: 'Thôn Phú Mỹ, Xã Tiến Thắng, Mê Linh, Hà Nội',
    priceLevel: 'FREE',
    galleryCaptions: [
      'Mặt tiền đình Phú Mỹ cổ kính',
      'Mái ngói điêu khắc cổ',
      'Sân đình rộng lớn',
    ],
    published: true,
  },
  {
    name: 'Mô hình dưa lưới',
    categoryCode: 'CUISINE',
    summary: 'Mô hình trồng dưa lưới tại thôn Thanh Vân là điểm sáng về ứng dụng nông nghiệp công nghệ cao.',
    description: 'Mô hình ứng dụng nông nghiệp công nghệ cao của bà con xã Tiến Thắng, mang lại quả dưa lưới chất lượng chuẩn VietGAP.',
    latitude: 21.2025,
    longitude: 105.677,
    bestTime: 'Trưa muộn hoặc chiều để tham quan nhà màng công nghệ cao.',
    localTip: 'Có thể mua dưa tại vườn làm quà biếu.',
    address: 'Thôn Thanh Vân, Xã Tiến Thắng, Mê Linh, Hà Nội',
    priceLevel: 'FREE',
    galleryCaptions: [
      'Mô hình dưa lưới tại thôn Thanh Vân',
      'Công nghệ tưới tiêu nhỏ giọt trong nhà màng',
      'Sản xuất dưa lưới ứng dụng chuyển đổi số',
    ],
    published: true,
  },
];
